name: pre prod build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ppe
    steps:
    - name: secret at ppe envioronment
      run: echo "env var is ${{ secrets.BASE_SECRET }}"
    - name: secret at repo level
      run: echo "repo secret is ${{ secrets.REPO_SECRET1 }}"
    - name: variable created at ppe environemnt
      run: echo "env var is ${{ vars.BASE_URL }}"
    - name: variable at repo level
      run: echo "repo var is ${{ vars.REPO_VAR1 }}"
    
