name: pre prod build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ppe
    steps:
    - name: env secret
      run: echo 'env var is {{BASE_SECRET}}'
    - name: repo secret
      run: echo 'repo secret is {{REPO_SECRET1}}'
    - name: env var
      run: echo 'env var is {{BASE_URL}}'
    - name: repo var
      run: echo 'repo var is {{REPO_VAR1}}'
    
