name: pre prod build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ppe
    steps:
    - name: env secret
      run: echo "env var is ${{ env.BASE_SECRET }}"
    - name: repo secret
      run: echo "repo secret is ${{ env.REPO_SECRET1 }}"
    - name: env var
      run: echo "env var is ${{ vars.BASE_URL }}"
    - name: repo var
      run: echo "repo var is ${{ vars.REPO_VAR1 }}"
    
